Kosak char sequence view
deephaven/deephaven-csv pull request #23
Opened 2022-03-15 00:39 UTC by kosak

Built on top of #21

2022-03-15 17:10 UTC, devinrsmith requested changes

2022-03-15 17:10 UTC, devinrsmith commented on src/main/java/io/deephaven/csv/containers/ByteSlice.java
> +    }
We should likely do explicit bounds checking to adhere to the CharSequence throws contracts.

2022-03-15 17:29 UTC, kosak commented on src/main/java/io/deephaven/csv/containers/ByteSlice.java
> +    }
done

2022-03-16 18:34 UTC, devinrsmith commented on src/main/java/io/deephaven/csv/containers/ByteSlice.java
> +    }
charat needs it too!

2022-03-17 05:18 UTC, kosak commented
I can't find your comment about fixing charAt, but nevertheless I have fixed charAt

2022-03-17 14:32 UTC, merged